"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Participant = { id: string; name: string; email?: string; contingent?: string; sport?: string; submittedAt?: string; status: string; notes?: string };
type RecordItem = { id?: string; title?: string; name?: string; date?: string; status?: string; gold?: string; silver?: string; bronze?: string; [key: string]: string | undefined };
const sections = [
  ["overview", "Ringkasan"], ["participants", "Pendaftaran Masuk"], ["news", "Berita"], ["medals", "Perolehan Medali"], ["agenda", "Agenda"], ["sponsors", "Sponsor"], ["organization", "Struktur Organisasi"], ["account", "Akun & Keamanan"],
];
const samples: Record<string, RecordItem[]> = {
  news: [{ id: "1", title: "Persiapan PORWANAS memasuki tahap akhir", date: "12 Agustus 2026", status: "Terbit" }, { id: "2", title: "Technical meeting dihadiri seluruh kontingen", date: "11 Agustus 2026", status: "Draft" }],
  medals: [{ id: "1", name: "Jawa Timur", gold: "10", silver: "7", bronze: "4" }, { id: "2", name: "DKI Jakarta", gold: "8", silver: "9", bronze: "5" }],
  agenda: [{ id: "1", title: "Registrasi Kontingen", date: "12 Agustus 2026 · 08.00 WIB" }, { id: "2", title: "Opening Ceremony", date: "12 Agustus 2026 · 19.00 WIB" }],
  sponsors: [{ id: "1", name: "Sponsor Utama", status: "Aktif" }, { id: "2", name: "Official Partner", status: "Aktif" }],
  organization: [{ id: "1", name: "Nama Ketua PORWANAS", title: "Ketua PORWANAS" }, { id: "2", name: "Nama Ketua Panitia", title: "Ketua Panitia" }],
};
const sampleParticipants: Participant[] = [{ id: "PRW-2026-000124", name: "Adi Setiawan", email: "adi@email.com", contingent: "Kalimantan Barat", sport: "Bulu Tangkis", submittedAt: "12 Agu 2026", status: "Menunggu" }, { id: "PRW-2026-000125", name: "Siti Rahma", email: "siti@email.com", contingent: "Jawa Timur", sport: "Sepak Bola", submittedAt: "12 Agu 2026", status: "Terverifikasi" }];

export default function AdminPage() {
  const [loggedIn, setLoggedIn] = useState(false); const [section, setSection] = useState("overview"); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("");
  const [participants, setParticipants] = useState<Participant[]>(sampleParticipants); const [content, setContent] = useState(samples); const [editing, setEditing] = useState<RecordItem | null>(null);
  async function api(action: string, extra = {}) { const r = await fetch(`/api/admin/data?action=${action}`, { method: action === "dashboard" || action === "participants" || action === "content" ? "GET" : "POST", headers: { "Content-Type": "application/json" }, body: action === "dashboard" || action === "participants" || action === "content" ? undefined : JSON.stringify({ action, ...extra }) }); const data = await r.json(); if (!data.ok) throw new Error(data.message); return data; }
  async function load() { try { const [dash, people] = await Promise.all([api("dashboard"), api("participants")]); if (dash.content) setContent(dash.content); if (people.items) setParticipants(people.items); } catch (e) { setNotice(e instanceof Error ? `${e.message} Dashboard sedang menampilkan contoh tampilan.` : "Mode contoh."); } }
  useEffect(() => { if (loggedIn) load(); }, [loggedIn]);
  async function login(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setNotice(""); const fd = new FormData(e.currentTarget); try { const r = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: fd.get("username"), password: fd.get("password") }) }); const data = await r.json(); if (!data.ok) throw new Error(data.message); setLoggedIn(true); } catch (err) { setNotice(err instanceof Error ? err.message : "Login gagal."); } finally { setLoading(false); } }
  async function updateStatus(person: Participant, status: string) { setParticipants((prev) => prev.map((p) => p.id === person.id ? { ...p, status } : p)); try { await api("updateParticipant", { id: person.id, status, notes: person.notes || "" }); setNotice(`Status ${person.name} diperbarui.`); } catch { setNotice("Mode contoh: status belum tersimpan sebelum Apps Script dipasang."); } }
  async function saveContent(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!editing) return; const item = Object.fromEntries(new FormData(e.currentTarget)) as RecordItem; const group = section; setContent((prev) => ({ ...prev, [group]: [...(prev[group] || []).filter((x) => x.id !== item.id), item] })); setEditing(null); try { await api("saveContent", { section: group, item }); setNotice("Konten disimpan."); } catch { setNotice("Mode contoh: konten belum tersimpan sebelum Apps Script dipasang."); } }
  if (!loggedIn) return <main className="admin-login"><div className="admin-login-card"><a className="brand" href="/"><span className="brand-mark">P</span><span><b>PORWANAS</b><small>ADMINISTRATOR</small></span></a><p className="eyebrow gold">DASHBOARD PENGELOLAAN</p><h1>Masuk ke Admin</h1><p>Kelola pendaftaran, verifikasi, dan konten website PORWANAS dalam satu tempat.</p><form onSubmit={login}><label>Username Admin<input required name="username" autoComplete="username" placeholder="Masukkan username" /></label><label>Password<input required name="password" type="password" autoComplete="current-password" placeholder="Masukkan password" /></label>{notice && <div className="admin-alert">{notice}</div>}<button className="admin-primary" disabled={loading}>{loading ? "Memeriksa..." : "Masuk ke Dashboard →"}</button></form><a className="back-site" href="/">← Kembali ke website</a></div></main>;
  const verified = participants.filter((p) => p.status === "Terverifikasi").length;
  return <main className="admin-app"><aside className="admin-sidebar"><a className="brand" href="/"><span className="brand-mark">P</span><span><b>PORWANAS</b><small>ADMINISTRATOR</small></span></a><nav>{sections.map(([key, label]) => <button key={key} className={section === key ? "active" : ""} onClick={() => { setSection(key); setEditing(null); }}>{label}{key === "participants" && <em>{participants.filter((p) => p.status === "Menunggu").length}</em>}</button>)}</nav><button className="logout" onClick={async () => { await fetch("/api/admin/logout", { method: "POST" }); setLoggedIn(false); }}>Keluar</button></aside>
    <section className="admin-main"><header className="admin-top"><div><p className="eyebrow gold">PANEL ADMIN</p><h1>{sections.find(([key]) => key === section)?.[1]}</h1></div><a href="/" target="_blank">Lihat Website ↗</a></header>{notice && <div className="admin-alert inline">{notice}<button onClick={() => setNotice("")}>×</button></div>}
      {section === "overview" && <><div className="stat-grid"><Stat label="Pendaftar Masuk" value={String(participants.length)} note="Total respons form"/><Stat label="Menunggu Verifikasi" value={String(participants.filter((p) => p.status === "Menunggu").length)} note="Butuh tindakan" warn/><Stat label="Terverifikasi" value={String(verified)} note="Tampil publik"/><Stat label="Berita Terbit" value={String(content.news.length)} note="Konten aktif"/></div><div className="admin-card"><div className="card-title"><div><p className="eyebrow gold">PERLU DITINDAKLANJUTI</p><h2>Pendaftaran Terbaru</h2></div><button className="plain" onClick={() => setSection("participants")}>Lihat Semua →</button></div><ParticipantTable participants={participants.slice(0, 5)} onStatus={updateStatus}/></div></>}
      {section === "participants" && <div className="admin-card"><div className="card-title"><div><p className="eyebrow gold">RESPONS GOOGLE FORM</p><h2>Data Pendaftar</h2></div><span className="count-pill">{participants.length} peserta</span></div><ParticipantTable participants={participants} onStatus={updateStatus}/></div>}
      {section === "account" && <AccountForm onDone={(message) => setNotice(message)} />}
      {section !== "overview" && section !== "participants" && section !== "account" && <div className="admin-card"><div className="card-title"><div><p className="eyebrow gold">KELOLA KONTEN</p><h2>{sections.find(([key]) => key === section)?.[1]}</h2></div><button className="admin-primary compact" onClick={() => setEditing({ id: crypto.randomUUID() })}>+ Tambah Data</button></div>{editing && <ContentForm section={section} item={editing} onClose={() => setEditing(null)} onSave={saveContent}/>}<ContentTable items={content[section] || []} onEdit={setEditing}/></div>}
    </section></main>;
}
function Stat({ label, value, note, warn }: { label: string; value: string; note: string; warn?: boolean }) { return <article className={`stat ${warn ? "warn" : ""}`}><p>{label}</p><b>{value}</b><span>{note}</span></article>; }
function ParticipantTable({ participants, onStatus }: { participants: Participant[]; onStatus: (p: Participant, s: string) => void }) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Peserta</th><th>Kontingen / Cabor</th><th>Registrasi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{participants.map((p) => <tr key={p.id}><td><b>{p.name}</b><small>{p.email}</small></td><td>{p.contingent}<small>{p.sport}</small></td><td><code>{p.id}</code><small>{p.submittedAt}</small></td><td><span className={`status ${p.status.toLowerCase().replaceAll(" ", "-")}`}>{p.status}</span></td><td>{p.status === "Menunggu" ? <><button className="verify" onClick={() => onStatus(p, "Terverifikasi")}>Verifikasi</button><button className="reject" onClick={() => onStatus(p, "Ditolak")}>Tolak</button></> : <button className="plain" onClick={() => onStatus(p, "Menunggu")}>Ubah</button>}</td></tr>)}</tbody></table></div> }
function ContentTable({ items, onEdit }: { items: RecordItem[]; onEdit: (item: RecordItem) => void }) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Nama / Judul</th><th>Informasi</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><b>{item.title || item.name}</b></td><td>{item.date || (item.gold ? `🥇 ${item.gold}  🥈 ${item.silver}  🥉 ${item.bronze}` : "—")}</td><td>{item.status || "Aktif"}</td><td><button className="plain" onClick={() => onEdit(item)}>Edit →</button></td></tr>)}</tbody></table></div> }
function ContentForm({ section, item, onClose, onSave }: { section: string; item: RecordItem; onClose: () => void; onSave: (e: FormEvent<HTMLFormElement>) => void }) { const fields = useMemo(() => section === "medals" ? ["name", "gold", "silver", "bronze"] : section === "organization" ? ["name", "title"] : section === "agenda" ? ["title", "date"] : ["title", "date", "status"], [section]); return <form className="content-form" onSubmit={onSave}>{fields.map((field) => <label key={field}>{field === "name" ? "Nama" : field === "title" ? "Judul" : field === "date" ? "Tanggal / Waktu" : field[0].toUpperCase() + field.slice(1)}<input name={field} defaultValue={item[field] || ""} required={field !== "status"} /></label>)}<input type="hidden" name="id" value={item.id}/><div><button type="button" className="cancel" onClick={onClose}>Batal</button><button className="admin-primary compact">Simpan</button></div></form> }
function AccountForm({ onDone }: { onDone: (message: string) => void }) { async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const data = Object.fromEntries(new FormData(form)); if (data.newPassword !== data.confirmPassword) return onDone("Konfirmasi password baru belum sama."); const response = await fetch("/api/admin/data", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "changeCredentials", oldPassword: data.oldPassword, newUsername: data.newUsername, newPassword: data.newPassword }) }); const result = await response.json(); if (!result.ok) return onDone(result.message || "Perubahan gagal."); form.reset(); onDone("Username dan password berhasil diubah. Gunakan data baru saat login berikutnya."); } return <div className="admin-card account-card"><p className="eyebrow gold">AKUN ADMIN</p><h2>Ubah Username & Password</h2><p>Demi keamanan, ubah password awal <code>admin</code> setelah backend tersambung.</p><form className="content-form account-form" onSubmit={submit}><label>Username Baru<input name="newUsername" required minLength={3} placeholder="contoh: admin_porwanas" /></label><label>Password Lama<input name="oldPassword" type="password" required /></label><label>Password Baru<input name="newPassword" type="password" minLength={8} required /></label><label>Ulangi Password Baru<input name="confirmPassword" type="password" minLength={8} required /></label><div><button className="admin-primary compact">Simpan Perubahan</button></div></form></div> }
